# Generated by Django 4.1.2 on 2022-10-19 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default=None, max_length=25)),
                ('lastname', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('date_joined', models.DateTimeField(default=datetime.datetime(2022, 10, 19, 19, 48, 8, 252720))),
                ('Email', models.EmailField(max_length=100, unique=True)),
                ('Mobile_No', models.CharField(blank=True, max_length=12, null=True)),
                ('Address', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('password', models.CharField(default=None, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
