# Generated by Django 4.1 on 2022-10-23 06:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_categories_remove_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_listed',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 23, 12, 24, 32, 768119)),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 23, 12, 24, 32, 765117)),
        ),
    ]
