# Generated by Django 4.1.2 on 2022-10-23 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_product_boast_clock_product_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='product_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='static/images/uploads/product_image/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_listed',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 23, 17, 31, 46, 64845)),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 23, 17, 31, 46, 40846)),
        ),
    ]
